### PR TITLE
use the system's patchelf executable if it is installed already

### PR DESCRIPTION
**Pull request by FelixSchwarz**
We would like to reduce the number of dependencies that are downloaded from third-party sources during the build process.

### CODE REVIEW

**Comment by quic-akhobare** [comment]
Thanks @FelixSchwarz - this change looks good to me.

@quic-emironov - could you please review and bless this?

**Comment by FelixSchwarz** [comment]
@quic-emironov , @quic-akhobare anything I can do here?

**Review by quic-bharathr — APPROVED** [review]

**Comment by quic-bharathr** [comment]
Thanks @FelixSchwarz for the reminder
@quic-emironov, could you please take a few minutes to review?

**Review by quic-emironov — APPROVED** [review]
Oh-oh! Sorry for late response. Looks good to me as well!

**Comment by FelixSchwarz** [comment]
Thank you. Now I just need someone to merge my PRs. :-)

**Pull request merged**
