### PR TITLE
Add TF1 bn reestimation support multiple branches

### LINKED ISSUE #1860: Add TF1 bn reestimation support multiple branches

### PR DESCRIPTION
**Pull request by quic-haijunz**
fixes #1860

### CODE REVIEW

**Comment by quic-akhobare** [comment]
@quic-sundarr  and @quic-haijunz - these commits should have been squashed to a smaller, more meaningful set. Is that the plan?

**Comment by quic-sundarr** [comment]
> @quic-sundarr and @quic-haijunz - these commits should have been squashed to a smaller, more meaningful set. Is that the plan?

Yes. Haijun is aware that we should keep a single relevant comment for the Open Source PR. I have also reminded him in the past. Thanks

**Comment by quic-akhobare** [comment]
> > @quic-sundarr and @quic-haijunz - these commits should have been squashed to a smaller, more meaningful set. Is that the plan?
> 
> Yes. Haijun is aware that we should keep a single relevant comment for the Open Source PR. I have also reminded him in the past. Thanks

It's not necessary to have a single commit. But if there are multiple commits - there should be good enough reason for each commit - plus each commit should be somewhat self-contained. If we ever need to backtrack it will be hard otherwise.

**Comment by quic-haijunz** [comment]
> > > @quic-sundarr and @quic-haijunz - these commits should have been squashed to a smaller, more meaningful set. Is that the plan?
> > 
> > 
> > Yes. Haijun is aware that we should keep a single relevant comment for the Open Source PR. I have also reminded him in the past. Thanks
> 
> It's not necessary to have a single commit. But if there are multiple commits - there should be good enough reason for each commit - plus each commit should be somewhat self-contained. If we ever need to backtrack it will be hard otherwise.

Thanks for your kind reminder.   for this PR  will squash into one single comment "Add TF1 bn re_estimation support multiple branches".     In future, multiple commits will follow above suggestions.

**Review by quic-sundarr — APPROVED** [review]
Please make sure to combine and simplify the commit messafges.

**Pull request merged**
